apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploymentrecreate
  namespace: default
  labels:
    app: nginx-deploymentrecreate
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-deploymentrecreate
  template:
    metadata:
      labels:
        app: nginx-deploymentrecreate
    spec:
      containers:
        - name: nginx
          image: index.docker.io/sreeharshav/testcontainer:v1
          ports:
            - containerPort: 8080
